/* /data/zb/src/ct_int.h: internal declarations shared by the ct.c modules (generated by splitting; keep in sync) */
#pragma once
#include "zb.h"
#define EV(n, s, o)                                                                                                    \
  do {                                                                                                                 \
    int r_ = ev(n, s, o);                                                                                              \
    if (r_ != R_OK) return r_;                                                                                         \
  } while (0)
#define EVR(n, s, t, o)                                                                                                \
  do {                                                                                                                 \
    int r_ = ev_rt(n, s, t, o);                                                                                        \
    if (r_ != R_OK) return r_;                                                                                         \
  } while (0)
#define ISNULL(v) ((v).k == CV_NULL && (v).slen <= 0)
#define ANON_HB 4096
#define ANON_CT_HB 1024

/* ct.c: the comptime interpreter.
   Evaluates AST nodes to CVal values. Used for constant folding (ceval), full comptime
   evaluation (ceval_force: comptime blocks/args/decl initializers), type functions, @typeInfo. */
#include "zb.h"

enum { R_FAIL, R_OK, R_CF };
enum { X_NONE, X_BRK, X_CONT, X_RET };
typedef struct AnonE {
  struct AnonE *next;
  unsigned h;
  Type *t;
} AnonE;
/* ---- wide comptime_int arithmetic (256-bit two's complement: hi:lo) ---- */
typedef unsigned __int128 u128;
typedef struct {
  i128 hi;
  u128 lo;
} W;

/* ---------- function calls ---------- */
typedef struct {
  Decl *fd;
  CVal *args;
  int n;
  CVal res;
} TMemo;

/* ---------- public entry points ---------- */
typedef struct {
  int force, xs;
  Type *rt;
  int lrt;
  Node *fail;
} CtSave;

/* shared state */
extern int xs;
extern char *xlabel;
extern CVal xval;
extern int ct_force;
extern long ct_steps;
extern Type *cur_rt;
extern Type *brt;
extern int ct_trace;
extern Type *t_splat;
extern char *lrt_l[64];
extern Type *lrt_t[64];
extern int lrt_n;
extern Node *ev_cur;
extern AnonE *anon_tab[ANON_HB];
extern AnonE *anon_ct_tab[ANON_CT_HB];
extern void **cp_k;
extern CVal **cp_p;
extern int *cp_f;
extern int cp_cap, cp_n;
extern Node *fail_node;
extern Vec tmemo;
extern Node *last_fail;

/* functions */
const char *ct_cur_loc(void);
long double f16_round_ld(long double f);
int f128_isnan(f128 x);
int f128_isinf(f128 x);
f128 f128_trunc(f128 x);
f128 f128_floor(f128 x);
f128 f128_ceil(f128 x);
f128 f128_round(f128 x);
f128 f128_sqrt(f128 x);
f128 fround(f128 f, Type *t);
CVal cv_float(f128 f, Type *t);
CVal cv_int(i128 i, Type *t);
CVal cv_bool(int b);
CVal cv_ty(Type *t);
CVal cv_void(void);
CVal cv_null(void);
CVal unwrap_some_null(CVal v);
CVal cv_undef(Type *t);
CVal cv_enumlit(const char *s);
CVal cv_str(const char *s, int len);
CVal *box(CVal v);
CVal cv_copy(CVal v);
int cv_is_mem(CVal *v);
Type *str_type(CVal *v);
Type *cv_typeof(CVal *v);
int ctonly_rec(Type *t, int depth);
int type_is_ctonly(Type *t);
int is_packed(Type *t);
Field *field_at(Type *t, int i);
int field_index(Type *t, const char *name);
CVal agg_new(Type *t);
int is_struct_like(Type *t);
int is_tuple_type(Type *t);
int is_anon(Type *t);
Type *mk_anon_struct(Vec *names, Vec *types, int tuple);
int ctf_eq(CVal *a, CVal *b);
Type *mk_anon_struct_cv(Vec *names, Vec *types, int tuple, CVal **cts);
Type *mk_anon_struct_new(Vec *names, Vec *types, int tuple);
int cv_len(CVal *v, int64_t *len);
CVal cv_elem(CVal *v, int64_t i);
CVal *elem_cell(CVal *v, int64_t i);
CVal *deref_cell(CVal *p);
void assign(CVal *cell, CVal v);
int cval_eq(CVal *a, CVal *b);
CVal mk_splat(CVal v);
CVal ccoerce(CVal v, Type *t);
CVal default_of(Type *t, Field *f);
int ceval_member(CVal base, const char *name, CVal *out);
int enum_of(CVal *lit, CVal *other);
int union_tag_is(CVal *u, CVal *tag);
CVal *as_cells(CVal *v, int64_t *len, Type **et);
int seq_is_str(CVal *v);
int ev_fbin(const char *op, CVal a, CVal b, CVal *out);
W to_w(CVal *v);
CVal from_w(W w);
W cw_add(W a, W b);
W cw_neg(W a);
int cw_cmp(W a, W b);
W cw_shl(W a, int n);
W cw_sar(W a, int n);
int cw_fits(W a);
int ev_bin_wide(const char *op, CVal a, CVal b, CVal *out);
int ev_bin(const char *op, CVal a, CVal b, CVal *out);
void step(void);
void bind_cap(Scope *s, char *name, CVal v);
CVal mk_union(Type *u, const char *field, CVal payload);
int ev_block(Node *n, Scope *s, CVal *out);
Type *rt_static_type(Scope *s, Node *n);
int ct_field_of(Scope *s, Node *n, CVal *out);
int is_local_array(Scope *s, Node *n, Type **at);
int fn_ret_type(Decl *fd, Scope *fs, Type **rt);
int fn_returns_ctonly(Decl *fd);
int fn_takes_ctonly(Decl *fd);
int self_arg(Node *recv, Scope *s, Scope *ps, CVal base, Node *param, CVal *out);
int ev_call_fn(Node *n, Scope *s, CVal fnv, int has_self, CVal self, Node *recv, CVal *out);
int ev_call(Node *n, Scope *s, CVal *out);
int ev_while(Node *n, Scope *s, CVal *out);
int ev_for(Node *n, Scope *s, CVal *out);
int item_matches(Node *it, Scope *s, CVal *v, int *m);
int ev_switch(Node *n, Scope *s, Type *rt, CVal *out);
int ev_slice(Node *n, Scope *s, CVal *out);
int base_cell(Node *a, Scope *s, CVal **cell);
CVal *cell_parent(CVal *c, int *fi);
void cp_put(CVal *c, CVal *par, int fi);
int clval(Node *n, Scope *s, CVal **cell);
int lv_const(Node *n, Scope *s);
int global_addr(Node *n, Scope *s, char **sym, int64_t *off, Type **t);
int ev(Node *n, Scope *s, CVal *out);
Type *lab_rt(const char *l);
int ev_if(Node *n, Scope *s, Type *rt, CVal *out);
CVal neg_like(CVal a, const char *op);
int ev_(Node *n, Scope *s, CVal *out);
Type *unwrap_rt(Type *t);
int ev_rt(Node *n, Scope *s, Type *rt, CVal *out);
int ev_init(Node *n, Scope *s, Type *t, CVal *out);
char *cv_name(CVal *v);
int ct_call(Decl *fd, CVal *args, int na, CVal *out);
Type *bt_type_pub(const char *path);
CVal cv_null_pub(void);
Type *bt_type(const char *path);
Type *ftype(Type *st, const char *name);
void setf(CVal *a, const char *name, CVal v);
CVal mk_struct(Type *t);
CVal slice_val(Type *st, CVal *items, int n);
CVal enum_lit_val(Type *et, const char *name);
CVal zstr(const char *s);
CVal ptr_to_val(CVal v);
CVal decls_val(Type *st, Container *c);
int ti17(void);
CVal names_val(Type *st, const char *fname, Container *c, int decls);
CVal type_info17(Type *T, const char **tagp);
CVal type_info(Type *T);
char *cv_cstr(CVal *v, int *lenp);
CVal seq_at(CVal *v, int64_t i);
int agg_get(CVal *a, const char *name, CVal *out);
int bits_of(Type *t);
int log2_bits(int b);
i128 umask(int bits);
int is_packed_union(Type *t);
int packed_type(Type *t);
i128 f_to_bits(f128 f, int bits);
f128 bits_to_f(i128 v, int bits);
i128 pack_val(CVal *v);
CVal unpack_val(i128 x, Type *t);
Type *peer_int(CVal *a, CVal *b);
CVal ovf_tuple(i128 r, Type *t);
Container *mk_container(int k, const char *name);
int cleaf_ok(Type *t);
int clbits(Type *t);
void cflat(CVal *a, Type *t, i128 *acc, int *off);
CVal cunflat(Type *t, i128 acc, int *off);
int ev_builtin(Node *n, Scope *s, CVal *out);
CtSave ct_enter(int force);
void ct_leave(CtSave sv);
int ceval(Node *n, Scope *s, CVal *out);
int ceval_force(Node *n, Scope *s, CVal *out);
int ceval_rt(Node *n, Scope *s, Type *rt, CVal *out);
int ceval_ret(Node *n, Scope *s, Type *rt, Type *fnrt, CVal *out, int *returned);
int ct_try_store(Node *dst, Node *n, Scope *s);
int ct_try_assign(Node *n, Scope *s);
Type *eval_type(Node *n, Scope *s);
Type *call_type_fn(Decl *d, Vec *argnodes, Scope *s);
const char *ct_fail_loc(void);
i128 cv_pack(CVal *v);
int cv_binop(const char *op, CVal a, CVal b, CVal *out);
int cv_match(CVal *v, CVal *item);
int ceval_ex(Node *n, Scope *s, Type *rt, CVal *out);
